NOTES = {
"Josh Allen":"Only QB to finish top-3 in fantasy PPG in each of the last five seasons, and hasn't missed a start. Every board has him alone in Tier 1.",
"Jahmyr Gibbs":"Only back averaging 21+ PPR PPG in each of the last two years. David Montgomery's exit to Houston removes the goal-line cap; Detroit's O-line slipping to 13th in PFF run block is the one worry.",
"Bijan Robinson":"Top-three fantasy RB each of the last two seasons: 1,400+ rushing yards and 60+ catches both years. Genuine 1A/1B with Gibbs.",
"Ashton Jeanty":"Low ankle sprain in an Aug. 23 practice. Fell seven spots to RB10 / No. 16 overall on the 8/25 4for4 update; Week 1 still unclear.",
"Jeremiyah Love":"No. 3 overall to Arizona, the highest RB taken since Barkley in 2018. Each of the last nine RBs drafted top-12 finished top-12 in fantasy as a rookie.",
"Kenneth Walker III":"Super Bowl MVP in Seattle, then 3 yr / $43.05M to Kansas City with $28.7M guaranteed. Rankers moved him up through camp.",
"Quinshon Judkins":"2025 ended on an ankle injury and fractured fibula. ESPN still has him around RB20.",
"Cam Skattebo":"Coming back from a major 2025 injury, which is exactly why Tyrone Tracy is a handcuff that matters.",
"Bucky Irving":"Injury history, Kenny Gainwell's arrival and Sean Tucker vulturing the goal line all push him down from where the talent says he belongs.",
"TreVeyon Henderson":"Hard to argue past low-end RB2 as long as New England keeps featuring Rhamondre Stevenson.",
"Jonathon Brooks":"Missed all of 2025 recovering from a second ACL tear. Carolina let Rico Dowdle walk and ignored RB in the draft, which is a real vote of confidence. ADP ~125.",
"Blake Corum":"The consensus No. 1 backup RB. 782 scrimmage yards and six TDs in year two, with the Rams' split projected near 60/40.",
"Tank Bigsby":"The Saquon handcuff, full stop.",
"Tyrone Tracy Jr.":"Averaged 16.9 touches and 12.9 PPR points across the 10 games Skattebo wasn't the clear lead back.",
"Jordan Mason":"Biggest RB mover on the 8/25 update - up 16 spots to RB36.",
"Kyle Monangai":"Forced his way into a committee as a seventh-round rookie: 41% of Chicago's snaps, 4.6 YPC on 169 carries.",
"Ja'Marr Chase":"One of only three receivers projected for 255+ half-PPR points.",
"Puka Nacua":"Led the league at 23.4 PPR points per game in 2025.",
"Malik Nabers":"Had a second procedure to remove a cyclops lesion after his ACL repair. Running routes in camp, but a full Week 1 is unlikely. ADP sliding.",
"A.J. Brown":"Traded to New England for a 2028 first and a 2027 fifth. Immediately Drake Maye's No. 1 and reunited with his first head coach.",
"Jaylen Waddle":"Traded to Denver for the No. 30, No. 94 and No. 130 picks. Clear value spike with Bo Nix.",
"Tetairoa McMillan":"2025 Offensive Rookie of the Year - 1,014 yards and seven TDs, most among rookie WRs.",
"Terry McLaurin":"A quad injury held him to 10 games and a 38-582-3 line. Still Washington's No. 1 if healthy.",
"Stefon Diggs":"Signed with his hometown team. Led the NFL with a 15.4% catch rate over expected, caught 83.3% of his targets, 2.4 yards per route run.",
"Parker Washington":"From Week 12 on he led Jacksonville at a 25% target share and 14.2 PPR PPG; over the final four games that hit 31% and 18.5.",
"Xavier Worthy":"Kansas City moved on from Marquise Brown and Smith-Schuster and added only a fifth-rounder. They still trust him as a starter.",
"Michael Wilson":"2025 was top-heavy - the big games came when Marvin Harrison was out. Fine at WR4 cost, not above it.",
"DK Metcalf":"Being drafted on name recognition. Right player, wrong offense.",
"Deebo Samuel":"Back in Shanahan's system and three years younger than Mike Evans. Unsexy, but he'll start and score.",
"Josh Downs":"Moving up from the slot to Indy's No. 2, working underneath opposite Tyler Warren.",
"Jalen Nailor":"Vegas's big offseason signing and their camp WR1, though Brock Bowers will lead that team in receiving.",
"Adonai Mitchell":"Set to start opposite Garrett Wilson for a team that will play from behind a lot. A popular late-round favorite.",
"Rashid Shaheed":"Was breaking out in New Orleans before the trade to Seattle. Should be Darnold's No. 2 and the deep threat opposite JSN.",
"De'Zhaun Stribling":"Rookie second-rounder, sixth WR off the board. Ricky Pearsall's season-ending knee surgery opened the door and Stribling has been San Francisco's best camp receiver.",
"Travis Hunter":"Target hierarchy in Jacksonville is genuinely unsettled with Brian Thomas Jr. healthy. Priced as a WR5 lottery ticket.",
"Jayden Higgins":"Conflicting August reporting - one outlet removed him for a torn ACL, others had him as C.J. Stroud's clear No. 2. Verify status before you draft him.",
"DJ Moore":"Gives Buffalo the dependable No. 1 they've been missing, and could beat his ADP.",
"Rome Odunze":"The steady one in Chicago while Luther Burden is the explosive one for Caleb Williams.",
"Carnell Tate":"A bet on talent plus Cam Ward's year two under Brian Daboll. Tenth in yards per route run and a 68.8% contested-catch rate in college.",
"KC Concepcion":"24th overall to Cleveland under new HC Todd Monken. Roughly 100 targets would have been a top-30 fantasy WR season last year.",
"Brock Bowers":"TE1 on most boards - best offense he's played in since entering the league.",
"Trey McBride":"Wore the crown as 2025's top-scoring tight end. Coin flip with Bowers.",
"Colston Loveland":"58-713-6 as a rookie with 90+ receiving yards in each of his final two regular-season games.",
"Tyler Warren":"76-817-4 as a rookie - immediately a core piece of the Colts offense.",
"Kyle Pitts Sr.":"Finally delivered: 88 catches, 928 yards, five TDs in 2025.",
"Harold Fannin Jr.":"72-731-6 as a 21-year-old rookie and a 22% target share, finishing TE6. Njoku's move to the Chargers clears the room entirely.",
"George Kittle":"Opened camp on PUP with the Achilles he tore in the 2025 playoffs. Reports point to Week 1, but nothing is guaranteed.",
"Travis Kelce":"Back at 37 on a one-year deal. 76-851 on 108 targets last year - volume intact, but 13 total TDs across three seasons is a career low.",
"Dalton Kincaid":"Fantasy's biggest TE wild card. An efficiency darling on a 38% snap share while Buffalo managed a knee issue.",
"T.J. Hockenson":"A 16% target share and 51-438-3, then a shoulder injury. Kyler Murray should help, but show me first.",
"Oronde Gadsden II":"Year-two path got crowded fast - the Chargers added both David Njoku and Charlie Kolar.",
"David Njoku":"Signed with the Chargers after Fannin pushed him down Cleveland's chart.",
"Patrick Mahomes":"Coming off December knee surgery. Says the knee feels great and hasn't missed a camp practice, but it has been years since he was a fantasy superstar.",
"Lamar Jackson":"Coming off a subpar, injury-marred year with steep declines in both passing and rushing.",
"Drake Maye":"Only Josh Allen outscored him among QBs in 2025 - and now he has A.J. Brown.",
"Caleb Williams":"Tied for eighth among QBs in fantasy points per game last season.",
"Cam Ward":"Real QB2 upside after Tennessee added Carnell Tate and put Brian Daboll in charge of the offense.",
"Kyler Murray":"Released by Arizona, signed a one-year deal in Minnesota.",
"Kirk Cousins":"The bridge in Las Vegas ahead of No. 1 overall pick Fernando Mendoza.",
"Deshaun Watson":"Named Cleveland's Week 1 starter by Todd Monken - a situation worth re-checking on draft day.",
"Tua Tagovailoa":"In an unresolved Atlanta competition with Michael Penix Jr.",
"Joe Burrow":"Held around QB4 despite the ceiling, purely on durability.",
"Aaron Rodgers":"Locked in as Pittsburgh's QB1 - their first repeat Week 1 starter since 2020-21.",
"Brandon Aubrey":"Top-projected kicker at roughly 116 half-PPR points.",
"Ka'imi Fairbairn":"44-of-48 on field goals in 15 games, tying the single-season record.",
}
