# Grouped by WHY the market is missing them, not by position.
CATS = [
 ("post-hype","Post-hype","The market already tried them once and got bored. Boredom is not evidence."),
 ("repriced","Role changed, price didn't","An offseason move or a depth-chart shift that ADP hasn't caught up to."),
 ("year-two","The second-year leap","Rookie-year efficiency without the volume. The volume is the part that arrives."),
 ("runway","Somebody else's injury","A door opened in the last three weeks and the price is still catching up."),
 ("buried","Buried by a bigger name","Drafters stop reading a depth chart after the first line."),
 ("free","Free in the last two rounds","Zero cost, real path to targets. Take the shot."),
]

SLEEPERS = {
"Jonathon Brooks":("post-hype","ADP ~125 · RB29",
 "A second ACL tear cost him all of 2025, so the market moved on. Carolina did the opposite: they let Rico Dowdle walk and ignored running back entirely in the draft. Dave Canales says he “looks like the guy that I remember.” He climbed nine spots on the 8/25 update and still costs a bench pick for a three-down RB1 outcome."),
"Xavier Worthy":("post-hype","WR46",
 "Kansas City moved on from Marquise Brown and Smith-Schuster and replaced them with a fifth-round rookie. That is a roster telling you who it trusts. Third year, fastest man out of the 2024 class, and the last starter standing."),
"Michael Wilson":("post-hype","Value past pick 100",
 "Jumped nearly eight spots after the first preseason game and is still cheap. The knock is fair — 2025 was top-heavy in the games Marvin Harrison missed. The counter is that Arizona's target tree is still thin behind Harrison."),
"Rashod Bateman":("post-hype","Late-round / waiver",
 "Five years of waiting has trained everyone to stop looking. He is still the perimeter starter on an offense that scores, and the cost is now nothing."),

"Parker Washington":("repriced","ADP 88.4 Yahoo / 102.7 ESPN",
 "From Week 12 on he led all Jacksonville receivers with a 25% target share and 14.2 PPR points per game. Over the final four games, playoffs included, that became a 31% target share and 18.5 per game on a 26-454-3 line. He is being drafted as though that stretch did not happen."),
"Stefon Diggs":("repriced","~Round 10",
 "Led the entire NFL in catch rate over expected at 15.4%, caught 83.3% of his targets, and ran 2.4 yards per route — fifth among everyone with 300+ routes. He has risen more than a round twice since signing in Washington and is still a round-10 pick."),
"Josh Downs":("repriced","WR43",
 "Moving out of the slot into Indianapolis's No. 2 job. That makes him Daniel Jones' primary underneath target working opposite Tyler Warren, which is a volume role at a WR4 price."),
"David Montgomery":("repriced","PPR RB24",
 "Traded to Houston and has already established himself on top of that backfield — RB24 in ADP against RB43 for Woody Marks. The name is familiar enough that nobody is excited, which is the whole point."),
"Harold Fannin Jr.":("repriced","TE6-ish cost",
 "72-731-6 and a 22% target share as a 21-year-old rookie, good for TE6. Then David Njoku left for the Chargers and handed him the entire room. The Cleveland quarterback situation is the only reason he is not priced higher."),
"Kenny Gainwell":("repriced","RB31",
 "The exact reason Bucky Irving's price fell is the reason Gainwell has standalone value. Tampa is running a real committee and only one half of it is being drafted."),

"Gunnar Helm":("year-two","TE28 — essentially free",
 "As a rookie he posted a 22.4% target-per-route-run rate and 1.45 yards per route, both better than Chig Okonkwo, on an 80% catch rate. Cam Ward gets more comfortable in year two and Helm becomes the security blanket. You can take him with your last pick."),
"Terrance Ferguson":("year-two","TE20s",
 "The buzziest name in Rams camp all summer, getting extended first-team reps from Sean McVay. Only 25 targets as a rookie but 21 yards per catch, and the Rams are visibly expanding his route tree."),
"Mason Taylor":("year-two","TE14-ish",
 "Led the Jets in both catches and targets as a rookie despite playing 13 games. Aaron Glenn named him a breakout candidate in mid-August, which is usually a coach telling you the target share is going up."),
"Tyler Shough":("year-two","QB17",
 "Strong down the stretch as a rookie, and New Orleans spent the offseason propping the offense up around him — Travis Etienne in, Jordyn Tyson drafted eighth overall. Projection models keep flagging him as a steal."),
"Emeka Egbuka":("year-two","WR18",
 "A rookie star through five weeks before leveling off, which drafters have read as the ceiling rather than the calibration period. Priced as a WR2 for a player with WR1 usage in front of him."),

"De'Zhaun Stribling":("runway","Up ~27 spots to ~pick 100",
 "The single biggest riser on the board over the last week, and it still may not be enough. Ricky Pearsall's season-ending knee surgery cleared the room and Stribling — a second-round rookie, sixth receiver drafted — has been San Francisco's best camp receiver."),
"Tyrone Tracy Jr.":("runway","RB50",
 "Averaged 16.9 touches and 12.9 PPR points across the 10 games Cam Skattebo was not the clear lead back. Skattebo is coming back from a major injury. This is the cheapest handcuff with a starter's outcome attached."),
"Jonah Coleman":("runway","Late-round",
 "Sits behind J.K. Dobbins and R.J. Harvey in Denver, and Dobbins' health is a perpetual red flag. Touchdown-dependent as an RB3, but he could lead that team in rushing scores."),
"Tank Bigsby":("runway","RB47",
 "Not a sleeper if Saquon plays 17 games. The full Barkley workload is one of maybe three handcuff outcomes in football that wins a league outright."),

"Adonai Mitchell":("buried","WR55-ish",
 "Set to start opposite Garrett Wilson for a team that will be playing from behind most weeks. Third-year receivers with a defined starting job and negative game script are how late-round WR rooms get won."),
"Rashid Shaheed":("buried","WR56-ish",
 "Was breaking out in New Orleans before the midseason trade to Seattle. Now he is Sam Darnold's No. 2 and the deep threat working opposite Smith-Njigba, and he is being drafted like a change-of-pace piece."),
"Jalen Nailor":("buried","WR67 — going very late",
 "Las Vegas's big offseason signing and their camp WR1. Brock Bowers will lead that team in receiving, but Nailor is the receiver to own there and he costs a WR5 pick."),
"Jayden Reed":("buried","WR45",
 "Green Bay's slot receiver in a room where the market is busy arguing about Golden and Watson. Availability is the real question, not talent."),
"Isaac TeSlaa":("buried","Waiver-adjacent",
 "Locked in as Detroit's No. 3 and a genuine red-zone body on one of the league's best offenses. One step forward makes him relevant."),

"Cyrus Allen":("free","Last round / undrafted",
 "A fifth-round rookie turning heads in Kansas City camp with a path to real Patrick Mahomes targets. There is no cost to being wrong here."),
"Jalen Coker":("free","Last round / undrafted",
 "An undrafted free agent who built a genuine connection with Bryce Young. Large frame, hard worker, and a third-year breakout is live if Carolina's passing game takes any step at all."),
"Nick Singleton":("free","Last round",
 "One of the best late stashes on the board — the talent and the opening to become a difference-maker in exactly the weeks the fantasy playoffs happen."),
"Baker Mayfield":("free","Rounds 12-13",
 "Routinely available in the 12th or 13th round. If you punt quarterback entirely, this is where you land and it is a fine place to land."),
"Greg Dulcich":("free","Undrafted",
 "In position to step forward as a second primary target in Miami. A late-round tight end with a defined role beats a late-round tight end without one."),
"Emmett Johnson":("free","Undrafted",
 "The rookie behind Kenneth Walker III in an offense that just paid $43M for its backfield. Handcuff logic, zero cost."),
}

TRAPS = [
 ("Makai Lemon","WR · PHI","A hamstring has kept him out of practice for two weeks and rankers have him down to WR65 — while his ADP is still WR46. Cheap and hurt is not the same as cheap and good."),
 ("DK Metcalf","WR · PIT","Right player, wrong offense. He is being drafted on name recognition, and the Pittsburgh passing game is not going to fund a WR3 season."),
 ("Jayden Higgins","WR · HOU","One outlet removed him entirely for a torn ACL while others had him as Stroud's clear No. 2. Do not spend a real pick until you have confirmed which is true."),
 ("Jordyn Tyson","WR · NO","The eighth overall pick going in the ninth round looks like an obvious value — but a hamstring dropped him nearly 34 spots and may linger toward Week 7."),
]
