# Ranks 151+ : depth pools. Ordered within position.
# Confidence: 151-300 medium (role/consensus inferred from 2026 reporting), 301+ low (verify team before drafting).

RB_TAIL = [
("Emmett Johnson","KC"),("Sean Tucker","TB"),("Trey Benson","ARI"),("Zach Charbonnet","SEA"),
("Woody Marks","HOU"),("Ray Davis","BUF"),("Isaac Guerendo","SF"),("Kaleb Johnson","PIT"),
("Roschon Johnson","CHI"),("Tyjae Spears","TEN"),("Jaydon Blue","DAL"),("Devin Neal","NO"),
("Ollie Gordon II","MIA"),("Will Shipley","PHI"),("Jarquez Hunter","LAR"),("Kimani Vidal","LAC"),
("Justice Hill","BAL"),("Samaje Perine","CIN"),("Jerome Ford","CLE"),("Trevor Etienne","CAR"),
("Sincere McCormick","LV"),("Antonio Gibson","NE"),("Kareem Hunt","KC"),("Jaleel McLaughlin","DEN"),
("Tyler Goodson","IND"),("Emanuel Wilson","GB"),("Craig Reynolds","DET"),("Chris Rodriguez Jr.","WAS"),
("DeeJay Dallas","ARI"),("Kendre Miller","NO"),("Jaylen Wright","MIA"),("Keaton Mitchell","BAL"),
("Tahj Brooks","CIN"),("Pierre Strong Jr.","CLE"),("Hassan Haskins","LAC"),("Dylan Laube","LV"),
("Audric Estime","DEN"),("Brashard Smith","KC"),("Ty Johnson","BUF"),("Sione Vaki","DET"),
("Michael Carter","ARI"),("Israel Abanikanda","NYJ"),("Khalil Herbert","IND"),("Elijah Mitchell","SF"),
("Deuce Vaughn","DAL"),("Rasheen Ali","BAL"),("Emari Demercado","ARI"),("Zamir White","LV"),
("Cody Schrader","SF"),("Chris Brooks","GB"),("Tyler Badie","DEN"),("Bam Knight","NYG"),
("Kalel Mullings","TEN"),("Cam Akers","MIN"),("Blake Watson","DEN"),("Jordan James","SF"),
("Damien Martinez","SEA"),("Kyle Juszczyk","SF"),("Raheem Mostert","LV"),("LeQuint Allen","JAX"),
("Phil Mafah","DAL"),("Marcus Yarns","DAL"),("Jarveon Howard","CIN"),("Ulysses Bentley IV","NO"),
("Kaytron Allen","PIT"),("Justice Ellison","CAR"),("Corey Kiner","LAR"),("Jacardia Wright","NE"),("Ty Chandler","MIN"),("Dameon Pierce","HOU"),("Nick Chubb","HOU"),
("Kenny McIntosh","SEA"),("Tyrion Davis-Price","NE"),("Jase McClellan","ATL"),("Carson Steele","KC"),
("Miles Sanders","DAL"),("Salvon Ahmed","MIA"),("Dare Ogunbowale","HOU"),("Terrell Jennings","JAX"),
("Nate Carter","NYG"),("Gary Brightwell","NYG"),("Isaiah Davis","NYJ"),("Patrick Taylor Jr.","NYJ"),
("Jawhar Jordan","IND"),("George Holani","SEA"),("Hunter Luepke","DAL"),("Dillon Johnson","SEA"),
]

WR_TAIL = [
("Jalen Coker","CAR"),("Isaac TeSlaa","DET"),("Jauan Jennings","MIN"),("Omar Cooper Jr.","NYJ"),
("Makai Lemon","PHI"),("Denzel Boston","CLE"),("Keon Coleman","BUF"),("Marvin Mims Jr.","DEN"),
("Elijah Moore","PHI"),("Tre Tucker","LV"),("Cyrus Allen","KC"),("Tory Horton","SEA"),
("Troy Franklin","DEN"),("Darnell Mooney","ATL"),("Xavier Legette","CAR"),("Christian Kirk","HOU"),
("Dontayvion Wicks","PHI"),("Jalen Royals","KC"),("Roman Wilson","PIT"),("Chimere Dike","TEN"),
("Elic Ayomanor","TEN"),("Andrei Iosivas","CIN"),("Luke McCaffrey","WAS"),("Jack Bech","LV"),
("Ryan Flournoy","DAL"),("Savion Williams","GB"),("Darius Slayton","NYG"),("Josh Palmer","BUF"),
("Tre Harris","LAC"),("Dyami Brown","JAX"),("Kyle Williams","NE"),("Jalen Tolbert","DAL"),
("Calvin Austin III","PIT"),("Xavier Hutchinson","HOU"),("Anthony Gould","IND"),("Beaux Collins","NYJ"),
("Tez Johnson","TB"),("Pat Bryant","DEN"),("Dont'e Thornton Jr.","LV"),("Jacob Cowing","SF"),
("Olamide Zaccheaus","CHI"),("Jaylin Lane","WAS"),("Bub Means","NO"),("Xavier Restrepo","TEN"),
("Ray-Ray McCloud III","ATL"),("KeAndre Lambert-Smith","LAC"),("Mecole Hardman","GB"),("Jake Bobo","SEA"),
("Malachi Corley","NYJ"),("Arian Smith","NYJ"),("DeMario Douglas","NE"),("Jermaine Burton","CIN"),
("Sterling Shepard","TB"),("Kameron Johnson","TB"),("Tyler Scott","CHI"),("Nikko Remigio","KC"),
("Brenden Rice","LAC"),("Ashton Dulin","IND"),("Mason Tipton","NO"),("KaVontae Turpin","DAL"),
("Justin Watson","HOU"),("Efton Chism III","NE"),("Junior Bergen","SF"),("Jonathan Mingo","DAL"),
("Kaden Prather","WAS"),("Ainias Smith","PHI"),("Tim Patrick","DET"),("Dareke Young","SEA"),
("Jalen Cropper","MIA"),("Nick Westbrook-Ikhine","MIA"),("Trenton Irwin","CIN"),("Tyquan Thornton","KC"),
("Isaiah Bond","CLE"),("Chris Tyree","BAL"),("Devin Duvernay","JAX"),("David Moore","CAR"),
("Braylon Allen","NYG"),("Zay Jones","ARI"),("Greg Dortch","ARI"),("Simi Fehoko","LAC"),("Ja'Lynn Polk","NE"),("Josh Reynolds","MIN"),("Robert Woods","PIT"),
("Malik Heath","GB"),("Michael Gallup","ATL"),("Tyler Johnson","LAR"),("Kendrick Bourne","NE"),
("Van Jefferson","TEN"),("Parris Campbell","PHI"),("Jamari Thrash","CLE"),("Casey Washington","ATL"),
("Xavier Gipson","NYJ"),("Tejhaun Palmer","ARI"),("Bo Melton","GB"),("Charlie Jones","CIN"),
("Ricky White III","LV"),("Isaiah Williams","DET"),("Dominic Lovett","DET"),("Jordan Whittington","LAR"),
("Britain Covey","LAR"),("Skyy Moore","SF"),("Tommy Mellott","LV"),("Traeshon Holden","LV"),
("Konata Mumpfield","ATL"),("Elijhah Badger","PHI"),("Chris Bell","GB"),("Antwane Wells Jr.","MIA"),
]

TE_TAIL = [
("Isaiah Likely","BAL"),("Oronde Gadsden II","LAC"),("Hunter Henry","NE"),("Zach Ertz","WAS"),
("Pat Freiermuth","PIT"),("Dalton Schultz","HOU"),("Kenyon Sadiq","NYJ"),("Gunnar Helm","TEN"),
("Terrance Ferguson","LAR"),("A.J. Barner","SEA"),("Greg Dulcich","MIA"),("Cade Otton","TB"),
("Evan Engram","DEN"),("Theo Johnson","NYG"),("Cole Kmet","CHI"),("Michael Mayer","LV"),
("Mike Gesicki","CIN"),("Elijah Arroyo","SEA"),("Juwan Johnson","NO"),("Ben Sinnott","WAS"),
("Charlie Kolar","LAC"),("Jake Tonges","SF"),("Darnell Washington","PIT"),("Luke Musgrave","GB"),
("Tip Reiman","ARI"),("Colby Parkinson","LAR"),("Brock Wright","DET"),("Adam Trautman","DEN"),
("Foster Moreau","NO"),("Tyler Conklin","LAC"),("Noah Fant","CIN"),("Chig Okonkwo","TEN"),
("Jonnu Smith","PIT"),("Grant Calcaterra","PHI"),("Josh Whyle","TEN"),("Ja'Tavion Sanders","CAR"),
("Elijah Higgins","ARI"),("Zack Kuntz","NYJ"),("Jared Wiley","KC"),("Jalin Conyers","GB"),("Cade Stover","HOU"),("Will Dissly","LAC"),("Dawson Knox","BUF"),
("Tucker Fisk","MIN"),("Johnny Mundt","MIN"),("Gerald Everett","CHI"),("Durham Smythe","CHI"),
("Stone Smartt","LAC"),("Brevyn Spann-Ford","DAL"),("Luke Schoonmaker","DAL"),("Michael Rigerman","NYG"),
("Daniel Bellinger","NYG"),("Erick All Jr.","CIN"),("Devin Culp","TB"),("Payne Durham","TB"),("Jelani Woods","NYG"),("Tanner Hudson","CIN"),
]

QB_TAIL = [
("Kyler Murray","MIN"),("Tyler Shough","NO"),("Jared Goff","DET"),("Daniel Jones","IND"),
("Justin Herbert","LAC"),("Patrick Mahomes","KC"),("Baker Mayfield","TB"),("Jordan Love","GB"),
("Malik Willis","MIA"),("C.J. Stroud","HOU"),("Sam Darnold","SEA"),("Bryce Young","CAR"),
("Cam Ward","TEN"),("Geno Smith","NYJ"),("Aaron Rodgers","PIT"),("Michael Penix Jr.","ATL"),
("Jacoby Brissett","ARI"),("Deshaun Watson","CLE"),("Kirk Cousins","LV"),("Tua Tagovailoa","ATL"),
("Fernando Mendoza","LV"),("J.J. McCarthy","MIN"),("Shedeur Sanders","CLE"),("Ty Simpson","LAR"),
("Jalen Milroe","SEA"),("Spencer Rattler","NO"),("Dillon Gabriel","CLE"),("Tanner McKee","PHI"),
("Jake Browning","CIN"),("Mac Jones","SF"),("Aidan O'Connell","LV"),("Jarrett Stidham","DEN"),
("Cooper Rush","BAL"),("Gardner Minshew","KC"),("Joe Milton III","DAL"),
]

DST = ["Denver Broncos","Philadelphia Eagles","Baltimore Ravens","Houston Texans","Detroit Lions",
"Pittsburgh Steelers","Minnesota Vikings","Buffalo Bills","Seattle Seahawks","Green Bay Packers",
"Los Angeles Chargers","Kansas City Chiefs","Arizona Cardinals","San Francisco 49ers","Los Angeles Rams",
"Washington Commanders","New England Patriots","Chicago Bears","Indianapolis Colts","Tampa Bay Buccaneers",
"Atlanta Falcons","Cleveland Browns","Jacksonville Jaguars","New York Jets","Dallas Cowboys",
"Carolina Panthers","Cincinnati Bengals","Las Vegas Raiders","New York Giants","Tennessee Titans",
"New Orleans Saints","Miami Dolphins"]

K = [("Brandon Aubrey","DAL"),("Cameron Dicker","LAC"),("Ka'imi Fairbairn","HOU"),("Cam Little","JAX"),
("Jake Bates","DET"),("Chris Boswell","PIT"),("Tyler Loop","BAL"),("Jason Myers","SEA"),
("Will Reichard","MIN"),("Jake Elliott","PHI"),("Harrison Butker","KC"),("Evan McPherson","CIN"),
("Chase McLaughlin","TB"),("Wil Lutz","DEN"),("Tyler Bass","BUF"),("Daniel Carlson","LV"),
("Matt Gay","WAS"),("Andres Borregales","NE"),("Cairo Santos","CHI"),("Brandon McManus","GB"),
("Chad Ryland","ARI"),("Joshua Karty","LAR"),("Eddy Pineiro","SF"),("Spencer Shrader","IND"),
("Dustin Hopkins","CLE"),("Graham Gano","NYG"),("Nick Folk","NYJ"),("Parker Romo","ATL"),
("Blake Grupe","NO"),("Ryan Fitzgerald","TEN"),("Riley Patterson","CAR"),("Jason Sanders","MIA")]
