# Ranks 1-150: anchored in researched 2026 preseason consensus
# (ESPN Mike Clay 8/19, Field Yates 8/24, 4for4/Bleacher Nation 8/25, PFF, NFL.com, The Big Lead 8/24, Yahoo)
TOP150 = [
("Jahmyr Gibbs","RB","DET"),("Bijan Robinson","RB","ATL"),("Ja'Marr Chase","WR","CIN"),
("Puka Nacua","WR","LAR"),("Christian McCaffrey","RB","SF"),("Jaxon Smith-Njigba","WR","SEA"),
("Amon-Ra St. Brown","WR","DET"),("Jonathan Taylor","RB","IND"),("De'Von Achane","RB","MIA"),
("James Cook III","RB","BUF"),("CeeDee Lamb","WR","DAL"),("Justin Jefferson","WR","MIN"),
("Derrick Henry","RB","BAL"),("Ashton Jeanty","RB","LV"),("Drake London","WR","ATL"),
("Chase Brown","RB","CIN"),("Brock Bowers","TE","LV"),("Saquon Barkley","RB","PHI"),
("Trey McBride","TE","ARI"),("Kenneth Walker III","RB","KC"),("Nico Collins","WR","HOU"),
("Rashee Rice","WR","KC"),("Jeremiyah Love","RB","ARI"),("Omarion Hampton","RB","LAC"),
("A.J. Brown","WR","NE"),("Chris Olave","WR","NO"),("Garrett Wilson","WR","NYJ"),
("Breece Hall","RB","NYJ"),("Josh Jacobs","RB","GB"),("Malik Nabers","WR","NYG"),
("Tetairoa McMillan","WR","CAR"),("Javonte Williams","RB","DAL"),("Zay Flowers","WR","BAL"),
("DeVonta Smith","WR","PHI"),("Emeka Egbuka","WR","TB"),("Travis Etienne Jr.","RB","NO"),
("Ladd McConkey","WR","LAC"),("Kyren Williams","RB","LAR"),("Davante Adams","WR","LAR"),
("George Pickens","WR","DAL"),("Jaylen Waddle","WR","DEN"),("Colston Loveland","TE","CHI"),
("Tyler Warren","TE","IND"),("Quinshon Judkins","RB","CLE"),("Cam Skattebo","RB","NYG"),
("Tee Higgins","WR","CIN"),("Bucky Irving","RB","TB"),("Josh Allen","QB","BUF"),
("Terry McLaurin","WR","WAS"),("Jameson Williams","WR","DET"),("Bhayshul Tuten","RB","JAX"),
("Rome Odunze","WR","CHI"),("DJ Moore","WR","BUF"),("D'Andre Swift","RB","CHI"),
("Harold Fannin Jr.","TE","CLE"),("David Montgomery","RB","HOU"),("Jadarian Price","RB","SEA"),
("TreVeyon Henderson","RB","NE"),("Kyle Pitts Sr.","TE","ATL"),("Carnell Tate","WR","TEN"),
("Courtland Sutton","WR","DEN"),("Stefon Diggs","WR","WAS"),("Jayden Daniels","QB","WAS"),
("Michael Pittman Jr.","WR","PIT"),("Rhamondre Stevenson","RB","NE"),("Marvin Harrison Jr.","WR","ARI"),
("Jaylen Warren","RB","PIT"),("Sam LaPorta","TE","DET"),("Tucker Kraft","TE","GB"),
("Lamar Jackson","QB","BAL"),("Rico Dowdle","RB","PIT"),("DK Metcalf","WR","PIT"),
("Parker Washington","WR","JAX"),("Luther Burden III","WR","CHI"),("Tony Pollard","RB","TEN"),
("Alec Pierce","WR","IND"),("Mike Evans","WR","SF"),("Drake Maye","QB","NE"),
("Kenny Gainwell","RB","TB"),("Christian Watson","WR","GB"),("Matthew Golden","WR","GB"),
("Jonathon Brooks","RB","CAR"),("Michael Wilson","WR","ARI"),("Brian Thomas Jr.","WR","JAX"),
("Chuba Hubbard","RB","CAR"),("Jakobi Meyers","WR","JAX"),("George Kittle","TE","SF"),
("Jalen Hurts","QB","PHI"),("Wan'Dale Robinson","WR","TEN"),("Jordan Addison","WR","MIN"),
("J.K. Dobbins","RB","DEN"),("Jordan Mason","RB","MIN"),("Khalil Shakir","WR","BUF"),
("Jayden Reed","WR","GB"),("Kyle Monangai","RB","CHI"),("Xavier Worthy","WR","KC"),
("Jake Ferguson","TE","DAL"),("Jacory Croskey-Merritt","RB","WAS"),("Rachaad White","RB","WAS"),
("Dallas Goedert","TE","PHI"),("Joe Burrow","QB","CIN"),("Aaron Jones Sr.","RB","MIN"),
("Blake Corum","RB","LAR"),("Quentin Johnston","WR","LAC"),("Deebo Samuel","WR","SF"),
("RJ Harvey","RB","DEN"),("Josh Downs","WR","IND"),("Travis Kelce","TE","KC"),
("Jaxson Dart","QB","NYG"),("Isiah Pacheco","RB","KC"),("Jalen Nailor","WR","LV"),
("Tyrone Tracy Jr.","RB","NYG"),("Marquise Brown","WR","PHI"),("Trevor Lawrence","QB","JAX"),
("Tyler Allgeier","RB","ATL"),("Dalton Kincaid","TE","BUF"),("Dylan Sampson","RB","CLE"),
("Keenan Allen","WR","IND"),("Rashid Shaheed","WR","SEA"),("Braelon Allen","RB","NYJ"),
("Dak Prescott","QB","DAL"),("T.J. Hockenson","TE","MIN"),("Caleb Douglas","WR","MIA"),
("Jordyn Tyson","WR","NO"),("Adonai Mitchell","WR","NYJ"),("Tank Bigsby","RB","PHI"),
("Tank Dell","WR","HOU"),("Jerry Jeudy","WR","CLE"),("Bo Nix","QB","DEN"),
("Malik Washington","WR","MIA"),("Jalen McMillan","WR","TB"),("Mason Taylor","TE","NYJ"),
("Calvin Ridley","WR","TEN"),("KC Concepcion","WR","CLE"),("Jaylin Noel","WR","HOU"),
("Brock Purdy","QB","SF"),("Travis Hunter","WR","JAX"),("Nick Singleton","RB","TEN"),
("Brenton Strange","TE","JAX"),("Ja'Kobi Lane","WR","BAL"),("Rashod Bateman","WR","BAL"),
("Matthew Stafford","QB","LAR"),("Devaughn Vele","WR","NO"),("Jonah Coleman","RB","DEN"),
("Kayshon Boutte","WR","NE"),("Zachariah Branch","WR","ATL"),("De'Zhaun Stribling","WR","SF"),
("David Njoku","TE","LAC"),("Caleb Williams","QB","CHI"),("Jayden Higgins","WR","HOU"),
]
